#!/usr/bin/env python3
import hashlib
import os
from pathlib import Path
import re
import secrets
import sys


N = int("894B645E89E1535BBDAD5B8B290650530801B18EBFBF5E8FAB3C82872A3E9BB7", 16)
G = 7
DEFAULT_EXPANSION = 2


def read_dotenv(path):
    values = {}
    if not path.exists():
        return values

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")

    return values


def latin_upper(value):
    return "".join(chr(ord(ch) - 32) if "a" <= ch <= "z" else ch for ch in value)


def verifier_for(username, password, salt):
    username = latin_upper(username)
    password = latin_upper(password)
    inner = hashlib.sha1(f"{username}:{password}".encode("utf-8")).digest()
    exponent = int.from_bytes(hashlib.sha1(salt + inner).digest(), "little")
    verifier = pow(G, exponent, N).to_bytes(32, "little")
    return username, verifier


def parse_accounts(value):
    accounts = []
    for entry in value.split(","):
        entry = entry.strip()
        if not entry:
            continue

        if ":" not in entry:
            raise ValueError(f"INITIAL_ACCOUNTS entry must be username:password, got {entry!r}")

        username, password = entry.split(":", 1)
        username = username.strip()
        password = password.strip()
        if not username or not password:
            raise ValueError(f"INITIAL_ACCOUNTS entry must include username and password, got {entry!r}")

        if not re.fullmatch(r"[A-Za-z0-9_.-]{1,32}", username):
            raise ValueError(f"Unsupported account name {username!r}; use 1-32 ASCII letters, numbers, '.', '_' or '-'")

        if len(password) > 16:
            raise ValueError(f"Password for {username!r} is too long for the 3.3.5a client; use 16 characters or fewer")

        accounts.append((username, password))

    return accounts


def sql_quote(value):
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def main():
    repo_root = Path(__file__).resolve().parents[1]
    values = read_dotenv(repo_root / ".env.example")
    values.update(read_dotenv(repo_root / ".env"))

    accounts = parse_accounts(values.get("INITIAL_ACCOUNTS", ""))
    output = repo_root / "generated" / "sql" / "init_accounts.sql"
    output.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "-- Generated by scripts/generate-accounts-sql.py; do not edit by hand.",
        "-- Creates initial player accounts only when they do not already exist.",
        "SET NAMES utf8mb4;",
        "USE `acore_auth`;",
    ]

    if accounts:
        rows = []
        for username, password in accounts:
            salt = secrets.token_bytes(32)
            username_upper, verifier = verifier_for(username, password, salt)
            rows.append(
                "("
                f"{sql_quote(username_upper)},"
                f"X'{salt.hex()}',"
                f"X'{verifier.hex()}',"
                f"{DEFAULT_EXPANSION},"
                "'',"
                "'',"
                "NOW()"
                ")"
            )

        lines.extend(
            [
                "INSERT INTO `account` (`username`, `salt`, `verifier`, `expansion`, `reg_mail`, `email`, `joindate`) VALUES",
                ",\n".join(rows),
                "ON DUPLICATE KEY UPDATE `username` = `username`;",
                "INSERT INTO `realmcharacters` (`realmid`, `acctid`, `numchars`)",
                "SELECT `realmlist`.`id`, `account`.`id`, 0",
                "FROM `realmlist`, `account`",
                "LEFT JOIN `realmcharacters` ON `realmcharacters`.`acctid` = `account`.`id`",
                "WHERE `realmcharacters`.`acctid` IS NULL;",
            ]
        )

    output.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"Wrote {output}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"generate-accounts-sql.py: {exc}", file=sys.stderr)
        raise SystemExit(1)
